sonar.projectKey=python-app
sonar.projectName=Python App CI CD
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/test_*.py,**/requirements.txt

sonar.tests=.
sonar.test.inclusions=**/test_*.py

sonar.language=py
sonar.sourceEncoding=UTF-8
